# -*- coding: utf-8 -*-
"""PRG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HU7jeE8ZO29WoKaaYkHmj40KLdzBIUQi
"""

zadana_slova = ["Matous", "Martin", "ahoj", "er", "es", "i", "a"]

for slovo in zadana_slova:
  delka_slova = len(slovo)
  print(f"{slovo} počet znaků: {delka_slova}")



if delka_slova >= 4:
  print(f"{slovo} počet znaků: {delka_slova}")
elif delka_slova < 3 and delka_slova > 1:
  print(f"{slovo} počet znaků: 2")
elif delka_slova == 1:
  print(f"{slovo} počet znaků: 1")

kandidati = ["Bruno", "Anežka"]
zamestnanci = ["František", "Bruno", "Anna", "Jakub", "Klára"]
bez_bruna = kandidati.copy()
bez_bruna.remove("Bruno")
print("Zaměstanci na začátku:", bez_bruna)
opakovani_kandidati = bez_bruna * 3
print("Nové jméno přidáno:", opakovani_kandidati)
spojeni_zamestnanci = zamestnanci + opakovani_kandidati
print("Nová jména vložena", spojeni_zamestnanci)

zamestnanci = ["František", "Bruno", "Anna", "Jakub", "Klára"]
print("Zaměstnanci")

tyden = ["Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek", "Sobota", "Neděle"]
print("Vyber den v týdnu:")
cislo_dne = 3
print("Den v týdnu:" + tyden[cislo_dne - 1])
print("Vyber počáteční písmeno:")
prvni_pismeno_dne = tyden[cislo_dne - 1][0]
tip_prvniho_pismena = str("s")
if 1 <= cislo_dne <= 7:
  print("Hodnota je v intervalu 1-7")
else:
  print("Hodnota není v intervalu 1-7")
if tip_prvniho_pismena == prvni_pismeno_dne:
  print("Hodnoty se shodují")
else:
  print("Hodnoty se neshodují")

user_1 = {
    "name": "Marek",
    "surname": "Snídaně"
}

user_email = "mareksnidane@gmail.com"

user_1["email"] = user_email

print("User#01", user_1, user_email)

employees = {
    "employee01" : {
        "name": "Marek",
        "surname": "Snídaně",
        "email": "mareksnidane@gmail.com"
    },
    "employee02" : {
        "name": "Matouš",
        "surname": "Svatouš",
        "email": "matoussvatous@gmail.com"
    },
    "employee03" : {
        "name": "anna",
        "surname": "ranna",
        "email": "annaranna@gmail.com"
    }

}
seznam_klicu =list(employees.keys())
hodnoty_klicu = list(employees.values())
print("Všechny klíče:", seznam_klicu)
print("Všechny hodnoty:", hodnoty_klicu)

employee03_data = employees["employee03"]
print("Všechny údaje k poslednímu zaměstnanci:")
for key, value in employee03_data.items():
  print(f"{key}: {value}")

id123 = {
   'jmeno': 'Thomas',
   'vek': 45,
   'zeme': 'Czechia',
   'mesto': 'Brno'
}
id124 = {
   'jmeno': 'Daniel',
   'vek': 34,
   'zeme': 'Czechia',
   'mesto': 'Prague'
}
id125 = {
   'jmeno': 'Eva',
   'vek': 43,
   'zeme': 'Czechia',
   'mesto': 'Olomouc'
}
databaze = {
   'id123': {},
   'id124': {},
   'id125': {}
}
databaze['id123'] = id123
databaze['id124'] = id124
databaze['id125'] = id125
print(databaze)

numbers_1 = [1, 2, 3, 4, 5, 6, 7, 8]
numbers_2 = [1, 2, 3, 4, 5, 6, 7, 8]

all_numbers = set(numbers_1) | set(numbers_2)
print("Sjednocené hodnoty ze zadání:", all_numbers)

numbers_1 = {1, 2, 3, 4}
numbers_2 = {3, 4, 5, 6}

nums_1_differences = numbers_1.difference(numbers_2)
print("Rozdílné hodnoty prvního setu oproti druhému:", nums_1_differences)

jmeno = input("Zadejte své jméno:")
heslo = input("Zadejte své heslo:")

uzivatel = {"Marek":"1234"}

if jmeno in uzivatel and uzivatel[jmeno] == heslo:
  if jmeno == "Marek" and heslo == "1234":
    print("Ahoj Marek vítej v aplikaci!")
  else:
    print("Uživatelské jméno nebo heslo nejsou vpořádku")
else:
  print("Uživatelské jméno nebo heslo nejsou vpořádku")

sequence = [1, 21, 5, 3, 5., 8, 321, 1 , 2, 2,32, 6, 9, 1, 4, 6, 3, 1 ,2,321]
 counts = {}
 for number in sequence:
    if number not in counts:
       counts[number] = 1
    else:
        counts[number] += 1
sorted_keys = sorted(counts.keys())
for key in sorted_keys:
    print(f"key:{key} value: {counts[key]}")

def print_board(board):
    for row in board:
        print(" | ".join(row))
    print()

def is_valid_move(board, move):
    if not move.isdigit():
        return False
    move = int(move)
    if move < 1 or move > 9:
        return False
    row, col = divmod(move - 1, 3)
    return board[row][col] == " "

def check_winner(board, symbol):
    for i in range(3):
        if board[i].count(symbol) == 3 or [board[j][i] for j in range(3)].count(symbol) == 3:
            return True
    if [board[i][i] for i in range(3)].count(symbol) == 3 or [board[i][2 - i] for i in range(3)].count(symbol) == 3:
        return True
    return False

def is_draw(board):
    return all(cell != " " for row in board for cell in row)

def tic_tac_toe():
    print("Welcome to Tic Tac Toe!")
    print("Hráči se střídají v umisťování svého symbolu (X nebo O) na mřížku 3x3. První hráč, který vytvoří řadu tří symbolů, vyhrává!")

    board = [[" " for _ in range(3)] for _ in range(3)]
    positions = [[str(i + j * 3 + 1) for i in range(3)] for j in range(3)]
    print("Pozice na hrací desce:")
    print_board(positions)

    current_player = "X"

    while True:
        print("Aktuální stav desky:")
        print_board(board)

        move = input(f"Hráči {current_player}, vyberte pozici (1-9): ")
        if not is_valid_move(board, move):
            print("Neplatný tah. Zkuste to znovu.")
            continue

        move = int(move)
        row, col = divmod(move - 1, 3)
        board[row][col] = current_player

        if check_winner(board, current_player):
            print_board(board)
            print(f"Hráč {current_player} vyhrává!")
            break

        if is_draw(board):
            print_board(board)
            print("Remíza!")
            break

        current_player = "O" if current_player == "X" else "X"

if __name__ == "__main__":
    tic_tac_toe()