# -*- coding: utf-8 -*-
"""Tic Tac Toe projekt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGcEOnCXHKme27uQBJNCqjkDOxShu-sC
"""

def print_board(board):
    for row in board:
        print(" | ".join(row))
    print()

def is_valid_move(board, move):
    if not move.isdigit():
        return False
    move = int(move)
    if move < 1 or move > 9:
        return False
    row, col = divmod(move - 1, 3)
    return board[row][col] == " "

def check_winner(board, symbol):
    for i in range(3):
        if board[i].count(symbol) == 3 or [board[j][i] for j in range(3)].count(symbol) == 3:
            return True
    if [board[i][i] for i in range(3)].count(symbol) == 3 or [board[i][2 - i] for i in range(3)].count(symbol) == 3:
        return True
    return False

def is_draw(board):
    return all(cell != " " for row in board for cell in row)

def tic_tac_toe():
    print("Welcome to Tic Tac Toe!")
    print("Hráči se střídají v umisťování svého symbolu (X nebo O) na mřížku 3x3. První hráč, který vytvoří řadu tří symbolů, vyhrává!")

    board = [[" " for _ in range(3)] for _ in range(3)]
    positions = [[str(i + j * 3 + 1) for i in range(3)] for j in range(3)]
    print("Pozice na hrací desce:")
    print_board(positions)

    current_player = "X"

    while True:
        print("Aktuální stav desky:")
        print_board(board)

        move = input(f"Hráči {current_player}, vyberte pozici (1-9): ")
        if not is_valid_move(board, move):
            print("Neplatný tah. Zkuste to znovu.")
            continue

        move = int(move)
        row, col = divmod(move - 1, 3)
        board[row][col] = current_player

        if check_winner(board, current_player):
            print_board(board)
            print(f"Hráč {current_player} vyhrává!")
            break

        if is_draw(board):
            print_board(board)
            print("Remíza!")
            break

        current_player = "O" if current_player == "X" else "X"

if __name__ == "__main__":
    tic_tac_toe()